# Generated by Django 5.2 on 2025-04-24 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlb_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team_seasons',
        ),
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
        migrations.RemoveField(
            model_name='team',
            name='year_founded',
        ),
        migrations.RemoveField(
            model_name='team',
            name='year_last',
        ),
        migrations.RemoveField(
            model_name='teamseason',
            name='games',
        ),
        migrations.AddField(
            model_name='playerseason',
            name='team_season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_seasons', to='mlb_data.teamseason'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
